/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bb3DCube: typeof import('./src/components/Bb3DCube/Bb3DCube.vue')['default']
    BbCascaderPicker: typeof import('./src/components/BbCascaderPicker/BbCascaderPicker.vue')['default']
    BbDatePicker: typeof import('./src/components/BbDatePicker/BbDatePicker.vue')['default']
    BbDateRangeFieldPicker: typeof import('./src/components/BbDateRangeFieldPicker/BbDateRangeFieldPicker.vue')['default']
    BbDateRangePicker: typeof import('./src/components/BbDateRangePicker/BbDateRangePicker.vue')['default']
    BbDialog: typeof import('./src/components/BbDialog/BbDialog.vue')['default']
    BbFloatingButton: typeof import('./src/components/BbFloatingButton/BbFloatingButton.vue')['default']
    BbImagesPicker: typeof import('./src/components/BbImagesPicker/BbImagesPicker.vue')['default']
    BbList: typeof import('./src/components/BbList/BbList.vue')['default']
    BbLoadingIcon: typeof import('./src/components/BbLoadingIcon/BbLoadingIcon.vue')['default']
    BbMultiplePicker: typeof import('./src/components/BbMultiplePicker/BbMultiplePicker.vue')['default']
    BbPagePicker: typeof import('./src/components/BbPagePicker/BbPagePicker.vue')['default']
    BbPicker: typeof import('./src/components/BbPicker/BbPicker.vue')['default']
    BbRotate: typeof import('./src/components/BbRotate/BbRotate.vue')['default']
    BbTabbar: typeof import('./src/components/BbTabbar/BbTabbar.vue')['default']
    BbTable: typeof import('./src/components/BbTable/BbTable.vue')['default']
    BbTabs: typeof import('./src/components/BbTabs/BbTabs.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCascader: typeof import('vant/es')['Cascader']
    VanCell: typeof import('vant/es')['Cell']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
